name: CI/CD Workflow

on:
  push:
    branches:
      - '**' # Kör vid push till alla branches
  pull_request:
    branches:
      - main # Kör tester på PR till main

jobs:
  unit-test:
    name: Run unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-unit

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test # Kör endast om unit-test-jobbet lyckas
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-integration

  ui-test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test] # Kör endast om test-jobbet lyckas
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Install System Dependencies
        run: npx playwright install-deps

      - name: Run Tests
        run: npm run test-ui

  # deploy:
  #   name: Deploy to Server
  #   runs-on: ubuntu-latest
  #   needs: [unit-test, integration-test, ui-test] # Kör endast om tidigare jobb lyckas
  #   environment:
  #     name: production 
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Kör endast på merge till main
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Deploy Application
  #       run: |
  #         echo "Deploying application..."
  #         # Lägg till din deploy-logik här, t.ex.:
  #         ssh user@your-server "cd /path/to/app && git pull && npm install && npm run build && pm2 restart all"
